### ISSUE TITLE
subir projeto vazio

### ISSUE THREAD

**Issue by VictorFZ** [ddbonato/cadastro_usuarios#1]
voce precisa subir o projeto console vazio pra eu comecar a contribuir!

**Comment by ddbonato** [comment]
Não sei se isso não ajaj

**Comment by VictorFZ** [comment]
Cria só o projeto no visual Studio . Aí aqui no github tem um lugar pra subir direto o arquivo . Aí você pega na pasta do windows mesmo

**Comment by ddbonato** [comment]
Pronto.
