### ISSUE TITLE
Criar uma lista estatica e salvar lista de usuarios la

### ISSUE THREAD

**Issue by VictorFZ** [ddbonato/cadastro_usuarios#5]

**Comment by ddbonato** [comment]
Lindamente

**Comment by ddbonato** [comment]
é melhor você fechar os inssues depois que ver se foi resolvido mesmo.

**Comment by ddbonato** [comment]
Ou então esperar você dizer que está certo dai eu fechar.

**Comment by VictorFZ** [comment]
Me coloca da permissao direto no projeto. Temos que fazer isso via Pull Request entao, pra ficar certo.

Adiciona meu user VictorFZ aqui:

https://github.com/ddbonato/cadastro_usuarios/settings/access

Com permissao de Manage

![image](https://user-images.githubusercontent.com/1192419/114878802-fdb51f80-9dd6-11eb-968b-51df42f54079.png)

**Comment by VictorFZ** [comment]
Maintain*

**Comment by VictorFZ** [comment]
Ah e a lista tem q ficar fora do metodo, hehe

**Comment by ddbonato** [comment]
> Ah e a lista tem q ficar fora do metodo, hehe

Mas tem que criar como se fosse uma classe? Em outro arquivo?

**Comment by ddbonato** [comment]
Fiz uma atualização. Espero que resolva esse 'inssue'

**Comment by ddbonato** [comment]
> Me coloca da permissao direto no projeto. Temos que fazer isso via Pull Request entao, pra ficar certo.
> 
> Adiciona meu user VictorFZ aqui:
> 
> https://github.com/ddbonato/cadastro_usuarios/settings/access
> 
> Com permissao de Manage
> 
> ![image](https://user-images.githubusercontent.com/1192419/114878802-fdb51f80-9dd6-11eb-968b-51df42f54079.png)

![Captura de Tela (20)](https://user-images.githubusercontent.com/47951283/114945107-23fead80-9e1f-11eb-8282-69fc3457b274.png)

Victor está peinding

**Comment by VictorFZ** [comment]
#6

**Comment by ddbonato** [comment]
é nao fechou sozinho
